----------
 __noname__ = {
   ["TURNON"] = {
     ["str"] = "打开";
     ["ghost_valid"] = false;
     ["id"] = "TURNON";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 150;
     ["fn"] = "function: 0xd522400, defined in (1753-1759)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["NET"] = {
     ["str"] = "捕捉";
     ["ghost_valid"] = false;
     ["id"] = "NET";
     ["canforce"] = true;
     ["code"] = 90;
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 3;
     ["instant"] = false;
     ["fn"] = "function: 0xf1fa890, defined in (901-910)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = false;
   }
   ["UNWRAP"] = {
     ["str"] = "打开";
     ["ghost_valid"] = false;
     ["id"] = "UNWRAP";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 155;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xa87d7b0, defined in (2262-2270)scripts/actions.lua";
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["STEALMOLEBAIT"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "STEALMOLEBAIT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 131;
     ["distance"] = 0.75;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xf45db90, defined in (1886-1892)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["CHECKTRAP"] = {
     ["str"] = "检查";
     ["ghost_valid"] = false;
     ["id"] = "CHECKTRAP";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 31;
     ["fn"] = "function: 0xd684ea0, defined in (806-811)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["RESETMINE"] = {
     ["str"] = "重置";
     ["ghost_valid"] = false;
     ["id"] = "RESETMINE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 113;
     ["fn"] = "function: 0xc87b3f0, defined in (1630-1635)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["CAST_NET"] = {
     ["str"] = "撒网";
     ["code"] = 25;
     ["id"] = "CAST_NET";
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["distance"] = 12;
     ["fn"] = "function: 0x15af7a60, defined in (2753-2765)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["priority"] = 10;
     ["rmb"] = true;
     ["mount_valid"] = true;
   }
   ["TURNOFF"] = {
     ["str"] = {
       ["GENERIC"] = "关闭";
       ["EMERGENCY"] = "紧急模式";
     }
     ["ghost_valid"] = false;
     ["id"] = "TURNOFF";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xb242b80, defined in (1766-1772)scripts/actions.lua";
     ["code"] = 149;
     ["strfn"] = "function: 0xd522420, defined in (1761-1764)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["PICK"] = {
     ["str"] = "采集";
     ["ghost_valid"] = false;
     ["id"] = "PICK";
     ["canforce"] = true;
     ["code"] = 98;
     ["extra_arrive_dist"] = "function: 0xbb441e0, defined in (65-75)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 0;
     ["instant"] = false;
     ["fn"] = "function: 0x13593f00, defined in (955-960)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = true;
   }
   ["SHAVE"] = {
     ["str"] = {
       ["GENERIC"] = "刮";
       ["SELF"] = "给自己刮胡子";
     }
     ["ghost_valid"] = false;
     ["id"] = "SHAVE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b270, defined in (1508-1515)scripts/actions.lua";
     ["code"] = 124;
     ["strfn"] = "function: 0xc87b250, defined in (1501-1506)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["USEKLAUSSACKKEY"] = {
     ["str"] = "解锁";
     ["ghost_valid"] = false;
     ["id"] = "USEKLAUSSACKKEY";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 158;
     ["fn"] = "function: 0xc87b4f0, defined in (1728-1736)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["DRY"] = {
     ["str"] = "晾干";
     ["ghost_valid"] = false;
     ["id"] = "DRY";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 47;
     ["fn"] = "function: 0xc87af90, defined in (1118-1131)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["SADDLE"] = {
     ["str"] = "上鞍";
     ["ghost_valid"] = false;
     ["id"] = "SADDLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 120;
     ["fn"] = "function: 0xf26b130, defined in (2149-2158)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["WINTERSFEAST_FEAST"] = {
     ["str"] = "享用";
     ["ghost_valid"] = false;
     ["id"] = "WINTERSFEAST_FEAST";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 161;
     ["fn"] = "function: 0x15af7ac0, defined in (2803-2806)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["STOPCHANNELING"] = {
     ["str"] = "停止施法";
     ["ghost_valid"] = false;
     ["id"] = "STOPCHANNELING";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 133;
     ["distance"] = 2.1;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xa87d750, defined in (2228-2233)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["CHOP"] = {
     ["str"] = "砍";
     ["ghost_valid"] = false;
     ["id"] = "CHOP";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 32;
     ["fn"] = "function: 0xabe1cb0, defined in (839-847)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["WRAPBUNDLE"] = {
     ["str"] = "打包";
     ["ghost_valid"] = false;
     ["id"] = "WRAPBUNDLE";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 162;
     ["fn"] = "function: 0xa87d790, defined in (2249-2260)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["HAMMER"] = {
     ["str"] = "敲";
     ["ghost_valid"] = false;
     ["id"] = "HAMMER";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 66;
     ["fn"] = "function: 0xa2dffc0, defined in (119-147)../mods/workshop-1852958031/modmain.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["CONSTRUCT"] = {
     ["str"] = {
       ["GENERIC"] = "建造";
       ["GENERIC_FMT"] = "建造{name}";
       ["STORE"] = "添加材料";
     }
     ["ghost_valid"] = false;
     ["id"] = "CONSTRUCT";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["stroverridefn"] = "function: 0xa87d7f0, defined in (2277-2287)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 36;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0xa87d810, defined in (2289-2291)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0x1a0dae60, defined in (2293-2350)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["LOOKAT"] = {
     ["str"] = "检查";
     ["ghost_valid"] = true;
     ["id"] = "LOOKAT";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 76;
     ["fn"] = "function: 0x14affe80, defined in (580-596)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = -3;
     ["mount_valid"] = true;
   }
   ["REPLATE"] = {
     ["str"] = {
       ["GENERIC"] = "换盘子";
       ["FMT"] = "更换{dish}";
     }
     ["ghost_valid"] = false;
     ["id"] = "REPLATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["stroverridefn"] = "function: 0xf082c40, defined in (2588-2598)scripts/actions.lua";
     ["code"] = 112;
     ["fn"] = "function: 0xad8c480, defined in (2822-2889)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["TOGGLE_DEPLOY_MODE"] = {
     ["str"] = {
       ["GENERIC"] = "栽种";
       ["PORTABLE"] = "放置";
       ["GROUNDTILE"] = "放置地皮";
       ["WATER"] = "下水";
       ["GATE"] = "建造大门";
       ["TURRET"] = "放置";
       ["WALL"] = "建造墙";
       ["FENCE"] = "建造栅栏";
     }
     ["ghost_valid"] = false;
     ["id"] = "TOGGLE_DEPLOY_MODE";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xa5f6f80, defined in (115-115)scripts/actions.lua";
     ["code"] = 146;
     ["strfn"] = "function: 0xd684e60, defined in (785-796)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 10;
     ["mount_valid"] = false;
   }
   ["ADDFUEL"] = {
     ["str"] = "添加燃料";
     ["ghost_valid"] = false;
     ["id"] = "ADDFUEL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 5;
     ["fn"] = "function: 0xc87afb0, defined in (1133-1145)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["EXTEND_PLANK"] = {
     ["str"] = "伸出";
     ["ghost_valid"] = false;
     ["id"] = "EXTEND_PLANK";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 50;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0xd3370e0, defined in (2704-2706)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xd3370c0, defined in (2699-2702)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["NUZZLE"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "NUZZLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 91;
     ["fn"] = "function: 0xc50bc80, defined in (2064-2069)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["EXTINGUISH"] = {
     ["str"] = "扑灭";
     ["ghost_valid"] = false;
     ["id"] = "EXTINGUISH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 51;
     ["fn"] = "function: 0xc87b2f0, defined in (1539-1548)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["GIVETOPLAYER"] = {
     ["str"] = "给予";
     ["ghost_valid"] = false;
     ["id"] = "GIVETOPLAYER";
     ["canforce"] = true;
     ["code"] = 61;
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 3;
     ["instant"] = false;
     ["fn"] = "function: 0xc87b050, defined in (1219-1234)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = false;
   }
   ["CASTUNSUMMON"] = {
     ["str"] = "返回";
     ["ghost_valid"] = false;
     ["id"] = "CASTUNSUMMON";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 24;
     ["distance"] = inf;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xc7d44b0, defined in (1847-1851)scripts/actions.lua";
     ["mount_valid"] = true;
   }
   ["MANUALEXTINGUISH"] = {
     ["str"] = "扑灭";
     ["ghost_valid"] = false;
     ["id"] = "MANUALEXTINGUISH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 83;
     ["fn"] = "function: 0x1a767e90, defined in (894-899)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["DIG"] = {
     ["str"] = "挖";
     ["ghost_valid"] = false;
     ["id"] = "DIG";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 41;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xc3d3df0, defined in (859-862)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["REEL"] = {
     ["str"] = {
       ["GENERIC"] = "上钩";
       ["CANCEL"] = "停止钓鱼";
       ["REEL"] = "收线";
     }
     ["ghost_valid"] = false;
     ["id"] = "REEL";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xa53eb90, defined in (928-940)scripts/actions.lua";
     ["code"] = 107;
     ["strfn"] = "function: 0xa53ebb0, defined in (942-953)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["TALKTO"] = {
     ["str"] = "交谈";
     ["ghost_valid"] = false;
     ["id"] = "TALKTO";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 140;
     ["fn"] = "function: 0xc5185a0, defined in (749-761)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = 3;
     ["mount_valid"] = true;
   }
   ["POLLINATE"] = {
     ["str"] = "授粉";
     ["ghost_valid"] = false;
     ["id"] = "POLLINATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 103;
     ["fn"] = "function: 0xc87b2b0, defined in (1523-1531)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["DROP"] = {
     ["str"] = {
       ["GENERIC"] = "丢弃";
       ["YOTC_ENTERRACE"] = "进入竞赛";
       ["SETMINE"] = "设置地雷";
       ["SETTRAP"] = "设置陷阱";
       ["PLACELANTERN"] = "放置";
       ["FREESOUL"] = "释放灵魂";
     }
     ["encumbered_valid"] = true;
     ["ghost_valid"] = false;
     ["id"] = "DROP";
     ["instant"] = false;
     ["code"] = 46;
     ["priority"] = -1;
     ["extra_arrive_dist"] = "function: 0xbb44220, defined in (89-99)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["is_relative_to_platform"] = true;
     ["strfn"] = "function: 0x14affe60, defined in (569-578)scripts/actions.lua";
     ["fn"] = "function: 0x14affe40, defined in (556-567)scripts/actions.lua";
     ["mount_valid"] = true;
   }
   ["MURDER"] = {
     ["str"] = "谋杀";
     ["ghost_valid"] = false;
     ["id"] = "MURDER";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 89;
     ["fn"] = "function: 0xc87b470, defined in (1663-1697)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = true;
   }
   ["ABANDON"] = {
     ["str"] = "遗弃";
     ["ghost_valid"] = false;
     ["id"] = "ABANDON";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 1;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xf26b190, defined in (2180-2192)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["FILL"] = {
     ["str"] = "装满";
     ["ghost_valid"] = false;
     ["id"] = "FILL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 56;
     ["fn"] = "function: 0xc87af70, defined in (1110-1116)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["UNPACK"] = {
     ["str"] = "Unpack";
     ["ghost_valid"] = false;
     ["id"] = "UNPACK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["mod_name"] = "workshop-1079538195";
     ["code"] = 2;
     ["priority"] = 0;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x102cb420, defined in (123-144)../mods/workshop-1079538195/modmain.lua";
     ["mount_valid"] = false;
   }
   ["INVESTIGATE"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "INVESTIGATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 71;
     ["fn"] = "function: 0xc87b330, defined in (1556-1566)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["LIGHT"] = {
     ["str"] = "点燃";
     ["ghost_valid"] = false;
     ["id"] = "LIGHT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 75;
     ["fn"] = "function: 0xa2e0030, defined in (151-183)../mods/workshop-1852958031/modmain.lua";
     ["encumbered_valid"] = false;
     ["priority"] = -4;
     ["mount_valid"] = false;
   }
   ["BOARDPLATFORM"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "BOARDPLATFORM";
     ["instant"] = false;
     ["code"] = 15;
     ["priority"] = 0;
     ["ghost_exclusive"] = false;
     ["customarrivecheck"] = "function: 0xbb441a0, defined in (45-49)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xa93c490, defined in (644-646)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["FISH_OCEAN"] = {
     ["str"] = "钓鱼";
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["instant"] = false;
     ["code"] = 58;
     ["id"] = "FISH_OCEAN";
     ["rmb"] = true;
     ["ghost_exclusive"] = false;
     ["customarrivecheck"] = "function: 0xbb44160, defined in (18-30)scripts/actions.lua";
     ["is_relative_to_platform"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xf1fa8d0, defined in (916-918)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["FERTILIZE"] = {
     ["str"] = "施肥";
     ["ghost_valid"] = false;
     ["id"] = "FERTILIZE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 55;
     ["fn"] = "function: 0x1a767e50, defined in (864-884)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["DISMANTLE"] = {
     ["str"] = "收回";
     ["ghost_valid"] = false;
     ["id"] = "DISMANTLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 42;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x1a0daf20, defined in (2391-2409)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["SLAUGHTER"] = {
     ["str"] = {
       ["BUTCHER"] = "礼貌的屠宰";
       ["DISEMBOWEL"] = "温柔的开膛";
       ["KILL"] = "精致的杀死";
       ["MURDER"] = "优雅的谋杀";
       ["SLAUGHTER"] = "谨慎的屠杀";
       ["EVISCERATE"] = "轻柔的挖除内脏";
     }
     ["ghost_valid"] = false;
     ["id"] = "SLAUGHTER";
     ["canforce"] = true;
     ["stroverridefn"] = "function: 0x1b3b6b70, defined in (2566-2571)scripts/actions.lua";
     ["code"] = 125;
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 0;
     ["instant"] = false;
     ["fn"] = "function: 0x1b3b6b90, defined in (2573-2586)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = false;
   }
   ["ABANDON_QUEST"] = {
     ["str"] = "遗弃";
     ["ghost_valid"] = false;
     ["id"] = "ABANDON_QUEST";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 2;
     ["fn"] = "function: 0xad8c460, defined in (2815-2820)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["MOUNT"] = {
     ["str"] = "骑";
     ["ghost_valid"] = false;
     ["id"] = "MOUNT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 87;
     ["rmb"] = true;
     ["encumbered_valid"] = true;
     ["fn"] = "function: 0x15af77a0, defined in (2125-2140)scripts/actions.lua";
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["GOHOME"] = {
     ["str"] = "回家";
     ["ghost_valid"] = false;
     ["id"] = "GOHOME";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 63;
     ["fn"] = "function: 0xc87b350, defined in (1568-1588)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["BRUSH"] = {
     ["str"] = "洗刷";
     ["ghost_valid"] = false;
     ["id"] = "BRUSH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 17;
     ["fn"] = "function: 0xf26b170, defined in (2171-2178)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["COOK"] = {
     ["str"] = "烹饪";
     ["ghost_valid"] = false;
     ["id"] = "COOK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["stroverridefn"] = "function: 0xc87af30, defined in (1006-1010)scripts/actions.lua";
     ["code"] = 37;
     ["fn"] = "function: 0xc87af50, defined in (1012-1108)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = true;
   }
   ["BUILD"] = {
     ["str"] = "建造";
     ["ghost_valid"] = false;
     ["id"] = "BUILD";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 18;
     ["fn"] = "function: 0xc87b130, defined in (1397-1401)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["JUMPIN"] = {
     ["str"] = {
       ["GENERIC"] = "跳入";
       ["HAUNT"] = "闹鬼";
     }
     ["ghost_valid"] = true;
     ["id"] = "JUMPIN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b390, defined in (1594-1606)scripts/actions.lua";
     ["code"] = 73;
     ["strfn"] = "function: 0xc87b370, defined in (1590-1592)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["GIVEALLTOPLAYER"] = {
     ["str"] = "全给";
     ["ghost_valid"] = false;
     ["id"] = "GIVEALLTOPLAYER";
     ["canforce"] = true;
     ["code"] = 60;
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 3;
     ["instant"] = false;
     ["fn"] = "function: 0xc87b070, defined in (1236-1252)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = false;
   }
   ["RAISE_SAIL"] = {
     ["str"] = "扬帆";
     ["ghost_valid"] = false;
     ["id"] = "RAISE_SAIL";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0xf082ca0, defined in (2616-2618)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 105;
     ["distance"] = 1.25;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xf082c80, defined in (2611-2614)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["GIVE"] = {
     ["str"] = {
       ["GENERIC"] = "给予";
       ["READY"] = "献祭";
       ["APPLY"] = "使用 {item}";
       ["SOCKET"] = "镶嵌";
       ["PLACE_ITEM"] = "放置{item}";
       ["QUAGMIRE_POT_HANGER"] = "悬挂{item}";
       ["NOTREADY"] = "放置";
       ["QUAGMIRE_ALTAR"] = {
         ["GENERIC"] = "祭上{food}";
         ["PLATE"] = "祭上一盘{food}";
         ["BOWL"] = "祭上一碗{food}";
       }
       ["QUAGMIRE_OVEN"] = "放置{item}";
       ["CELESTIAL"] = "提供";
     }
     ["ghost_valid"] = false;
     ["id"] = "GIVE";
     ["canforce"] = true;
     ["stroverridefn"] = "function: 0xc87b010, defined in (1168-1196)scripts/actions.lua";
     ["instant"] = false;
     ["code"] = 59;
     ["ghost_exclusive"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 0;
     ["strfn"] = "function: 0xc87aff0, defined in (1161-1166)scripts/actions.lua";
     ["fn"] = "function: 0xc87b030, defined in (1198-1217)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = true;
   }
   ["EQUIP"] = {
     ["str"] = "装备";
     ["ghost_valid"] = false;
     ["id"] = "EQUIP";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 49;
     ["fn"] = "function: 0xc79e810, defined in (385-389)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["MIGRATE"] = {
     ["str"] = "游历";
     ["ghost_valid"] = true;
     ["id"] = "MIGRATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 84;
     ["fn"] = "function: 0x15af7740, defined in (2097-2103)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["CATCH"] = {
     ["str"] = "捕捉";
     ["ghost_valid"] = false;
     ["id"] = "CATCH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 26;
     ["distance"] = inf;
     ["encumbered_valid"] = false;
     ["priority"] = 3;
     ["fn"] = "function: 0xf1fa8b0, defined in (912-914)scripts/actions.lua";
     ["mount_valid"] = true;
   }
   ["REPAIR"] = {
     ["str"] = {
       ["GENERIC"] = "修理";
       ["SOCKET"] = "开槽";
     }
     ["ghost_valid"] = false;
     ["id"] = "REPAIR";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xf60be60, defined in (476-492)scripts/actions.lua";
     ["code"] = 110;
     ["strfn"] = "function: 0xf60be40, defined in (470-474)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["READ"] = {
     ["str"] = "阅读";
     ["ghost_valid"] = false;
     ["id"] = "READ";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 106;
     ["fn"] = "function: 0x13e28ce0, defined in (598-606)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["TELEPORT"] = {
     ["str"] = {
       ["GENERIC"] = "使用";
       ["TOWNPORTAL"] = "触摸";
     }
     ["priority"] = 0;
     ["code"] = 143;
     ["ghost_valid"] = false;
     ["id"] = "TELEPORT";
     ["distance"] = 2;
     ["fn"] = "function: 0xc87b3d0, defined in (1612-1628)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["strfn"] = "function: 0xc87b3b0, defined in (1608-1610)scripts/actions.lua";
     ["rmb"] = true;
     ["mount_valid"] = true;
   }
   ["ACTIVATE"] = {
     ["str"] = {
       ["GENERIC"] = "激活";
       ["SPELUNK"] = "洞穴探险";
       ["CLIMB"] = "攀爬";
       ["CLOSE"] = "关闭";
       ["TOUCH"] = "触摸";
       ["INVESTIGATE"] = "调查";
       ["OPEN"] = "打开";
       ["ACCOMPLISH"] = "上发条";
     }
     ["ghost_valid"] = false;
     ["id"] = "ACTIVATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b410, defined in (1637-1642)scripts/actions.lua";
     ["code"] = 4;
     ["strfn"] = "function: 0xc87b430, defined in (1644-1648)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["JOIN"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "JOIN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 72;
     ["fn"] = "function: 0x1b3b6ab0, defined in (115-115)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["FEEDPLAYER"] = {
     ["str"] = "喂养";
     ["ghost_valid"] = false;
     ["id"] = "FEEDPLAYER";
     ["canforce"] = true;
     ["code"] = 54;
     ["rmb"] = true;
     ["ghost_exclusive"] = false;
     ["instant"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xc87b090, defined in (1254-1289)scripts/actions.lua";
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["UNSADDLE"] = {
     ["str"] = "卸下";
     ["ghost_valid"] = false;
     ["id"] = "UNSADDLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 154;
     ["fn"] = "function: 0xf26b150, defined in (2160-2169)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["APPLYPRESERVATIVE"] = {
     ["str"] = {
       ["GENERIC"] = "腌制";
       ["SALT"] = "腌制";
     }
     ["ghost_valid"] = false;
     ["id"] = "APPLYPRESERVATIVE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0x1062f980, defined in (2436-2461)scripts/actions.lua";
     ["code"] = 8;
     ["strfn"] = "function: 0x1062f960, defined in (2432-2434)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["UNPIN"] = {
     ["str"] = "分开";
     ["ghost_valid"] = false;
     ["id"] = "UNPIN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 153;
     ["fn"] = "function: 0xf45db70, defined in (1879-1884)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["UNLOCK"] = {
     ["str"] = {
       ["GENERIC"] = "解锁";
       ["LOCK"] = "锁定";
     }
     ["ghost_valid"] = false;
     ["id"] = "UNLOCK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 152;
     ["fn"] = "function: 0xc87b4d0, defined in (1717-1726)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["ATTUNE"] = {
     ["str"] = "附体";
     ["ghost_valid"] = false;
     ["id"] = "ATTUNE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 10;
     ["fn"] = "function: 0x15af7720, defined in (2089-2095)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["EAT"] = {
     ["str"] = "吃";
     ["ghost_valid"] = false;
     ["id"] = "EAT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 48;
     ["fn"] = "function: 0xd2e1530, defined in (337-348)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["SLEEPIN"] = {
     ["str"] = "睡觉";
     ["ghost_valid"] = false;
     ["id"] = "SLEEPIN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 126;
     ["fn"] = "function: 0xc87b1f0, defined in (1466-1477)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["SMOTHER"] = {
     ["str"] = "扑灭";
     ["ghost_valid"] = false;
     ["id"] = "SMOTHER";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 127;
     ["fn"] = "function: 0x1a767e70, defined in (886-892)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["STORE"] = {
     ["str"] = {
       ["GENERIC"] = "存放";
       ["IMPRISON"] = "关入鸟笼";
       ["DECORATE"] = "装饰";
       ["COOK"] = "烹饪";
       ["SPICE"] = "调味";
     }
     ["ghost_valid"] = false;
     ["id"] = "STORE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b0d0, defined in (1298-1374)scripts/actions.lua";
     ["code"] = 136;
     ["strfn"] = "function: 0xc87b110, defined in (1388-1395)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["DECORATEVASE"] = {
     ["str"] = "装饰";
     ["ghost_valid"] = false;
     ["id"] = "DECORATEVASE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 39;
     ["fn"] = "function: 0xc87b0b0, defined in (1291-1296)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["REMOTERESURRECT"] = {
     ["str"] = "复活";
     ["ghost_valid"] = true;
     ["id"] = "REMOTERESURRECT";
     ["instant"] = false;
     ["ghost_exclusive"] = true;
     ["code"] = 108;
     ["fn"] = "function: 0x15af7760, defined in (2105-2113)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["MINE"] = {
     ["str"] = "开采";
     ["ghost_valid"] = false;
     ["id"] = "MINE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 85;
     ["fn"] = "function: 0xc3d3db0, defined in (849-852)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["FEED"] = {
     ["str"] = "喂养";
     ["ghost_valid"] = false;
     ["id"] = "FEED";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 53;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xf45dbf0, defined in (1911-1994)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["PACK"] = {
     ["str"] = "Pack";
     ["ghost_valid"] = false;
     ["id"] = "PACK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["mod_name"] = "workshop-1079538195";
     ["code"] = 1;
     ["priority"] = 10;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x1a447340, defined in (90-107)../mods/workshop-1079538195/modmain.lua";
     ["mount_valid"] = false;
   }
   ["ROW_CONTROLLER"] = {
     ["str"] = "划";
     ["code"] = 117;
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["instant"] = false;
     ["id"] = "ROW_CONTROLLER";
     ["priority"] = 3;
     ["ghost_exclusive"] = false;
     ["do_not_locomote"] = true;
     ["is_relative_to_platform"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x19f50180, defined in (640-642)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["ROW"] = {
     ["str"] = "划";
     ["code"] = 116;
     ["id"] = "ROW";
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["instant"] = false;
     ["priority"] = 3;
     ["is_relative_to_platform"] = true;
     ["ghost_exclusive"] = false;
     ["customarrivecheck"] = "function: 0xbb44180, defined in (31-43)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x19f50140, defined in (636-638)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["ROW_FAIL"] = {
     ["str"] = "划";
     ["code"] = 118;
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["instant"] = false;
     ["id"] = "ROW_FAIL";
     ["priority"] = 0;
     ["ghost_exclusive"] = false;
     ["customarrivecheck"] = "function: 0xd2e1220, defined in (316-316)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x13e28d00, defined in (608-620)scripts/actions.lua";
     ["skip_locomotor_facing"] = true;
     ["mount_valid"] = false;
   }
   ["WALKTO"] = {
     ["str"] = "走向";
     ["ghost_valid"] = true;
     ["id"] = "WALKTO";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 159;
     ["fn"] = "function: 0xcf23470, defined in (115-115)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = -4;
     ["mount_valid"] = true;
   }
   ["BATHBOMB"] = {
     ["str"] = "投掷";
     ["ghost_valid"] = false;
     ["id"] = "BATHBOMB";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 12;
     ["fn"] = "function: 0xf082c60, defined in (2600-2609)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["MOUNT_PLANK"] = {
     ["str"] = "骑";
     ["ghost_valid"] = false;
     ["id"] = "MOUNT_PLANK";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 88;
     ["distance"] = 0.5;
     ["strfn"] = "function: 0xd213a70, defined in (2678-2680)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xd213a50, defined in (2674-2676)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["FAN"] = {
     ["str"] = "扇风";
     ["ghost_valid"] = false;
     ["id"] = "FAN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 52;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xc50bc20, defined in (2031-2035)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["TACKLE"] = {
     ["str"] = "冲撞";
     ["code"] = 138;
     ["ghost_valid"] = false;
     ["id"] = "TACKLE";
     ["distance"] = inf;
     ["fn"] = "function: 0x1062f920, defined in (2411-2415)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["rmb"] = true;
     ["mount_valid"] = false;
   }
   ["SET_HEADING"] = {
     ["str"] = "设定航向";
     ["ghost_valid"] = false;
     ["id"] = "SET_HEADING";
     ["instant"] = false;
     ["code"] = 122;
     ["ghost_exclusive"] = false;
     ["do_not_locomote"] = true;
     ["distance"] = 9999;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x15af7a20, defined in (2738-2744)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["REPAIR_LEAK"] = {
     ["str"] = "补漏";
     ["ghost_valid"] = false;
     ["id"] = "REPAIR_LEAK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 111;
     ["distance"] = 2.5;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xd337140, defined in (2717-2721)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["APPLYCONSTRUCTION"] = {
     ["str"] = "建造";
     ["ghost_valid"] = false;
     ["id"] = "APPLYCONSTRUCTION";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 7;
     ["distance"] = 2;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x1a0daec0, defined in (2366-2377)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["CASTAOE"] = {
     ["str"] = {
       ["GENERIC"] = "施放法术";
       ["BOOK_ELEMENTAL"] = "召唤岩浆魔像";
       ["BLOWDART_LAVA2"] = "火球";
       ["SPEAR_LANCE"] = "冲天刺";
       ["LAVAARENA_FIREBOMB"] = "炉火炸弹";
       ["BOOK_FOSSIL"] = "石化";
       ["BLOWDART_LAVA"] = "齐射";
       ["FIREBALLSTAFF"] = "召唤灾难流星";
       ["LAVAARENA_HEAVYBLADE"] = "挡开";
       ["HEALINGSTAFF"] = "施放生命花";
       ["HAMMER_MJOLNIR"] = "铁砧攻击";
       ["LAVAARENA_LUCY"] = "投掷露西";
       ["SPEAR_GUNGNIR"] = "火刺";
     }
     ["priority"] = 10;
     ["code"] = 21;
     ["ghost_valid"] = false;
     ["id"] = "CASTAOE";
     ["distance"] = 8;
     ["fn"] = "function: 0x1a0daf00, defined in (2383-2389)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["strfn"] = "function: 0x1a0daee0, defined in (2379-2381)scripts/actions.lua";
     ["rmb"] = true;
     ["mount_valid"] = false;
   }
   ["STEER_BOAT"] = {
     ["str"] = "掌舵";
     ["ghost_valid"] = false;
     ["id"] = "STEER_BOAT";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0xd337160, defined in (2723-2725)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 132;
     ["distance"] = 0.1;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x15af7a00, defined in (2727-2736)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["CREATE"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "CREATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 38;
     ["fn"] = "function: 0x1b3b6940, defined in (115-115)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["GIVE_TACKLESKETCH"] = {
     ["str"] = "给予";
     ["ghost_valid"] = false;
     ["id"] = "GIVE_TACKLESKETCH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 62;
     ["fn"] = "function: 0x15af7a80, defined in (2767-2781)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["CHANGEIN"] = {
     ["str"] = {
       ["GENERIC"] = "使用";
       ["DRESSUP"] = "打扮";
     }
     ["ghost_valid"] = false;
     ["id"] = "CHANGEIN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b230, defined in (1483-1499)scripts/actions.lua";
     ["code"] = 29;
     ["strfn"] = "function: 0xc87b210, defined in (1479-1481)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = -1;
     ["mount_valid"] = false;
   }
   ["ABANDON_SHIP"] = {
     ["str"] = "弃船";
     ["ghost_valid"] = false;
     ["id"] = "ABANDON_SHIP";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0xd3370a0, defined in (2695-2697)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 3;
     ["distance"] = 2.5;
     ["encumbered_valid"] = false;
     ["priority"] = 4;
     ["fn"] = "function: 0xd213ad0, defined in (2691-2693)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["SALT"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "SALT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 121;
     ["fn"] = "function: 0xad8c4a0, defined in (2891-2924)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["LOWER_ANCHOR"] = {
     ["str"] = "下";
     ["ghost_valid"] = false;
     ["id"] = "LOWER_ANCHOR";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 77;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0xd213a30, defined in (2670-2672)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xd213a10, defined in (2666-2668)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["RUMMAGE"] = {
     ["str"] = {
       ["GENERIC"] = "打开";
       ["CLOSE"] = "关闭";
       ["DECORATE"] = "装饰";
     }
     ["ghost_valid"] = false;
     ["id"] = "RUMMAGE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc2ad550, defined in (509-543)scripts/actions.lua";
     ["code"] = 119;
     ["strfn"] = "function: 0xc2ad570, defined in (545-554)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = -1;
     ["mount_valid"] = true;
   }
   ["RAISE_ANCHOR"] = {
     ["str"] = "起";
     ["ghost_valid"] = false;
     ["id"] = "RAISE_ANCHOR";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 104;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0x15af7c30, defined in (2662-2664)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0x15af7c10, defined in (2658-2660)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["LOWER_SAIL_FAIL"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "LOWER_SAIL_FAIL";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0x15af7bf0, defined in (2653-2655)scripts/actions.lua";
     ["code"] = 80;
     ["ghost_exclusive"] = false;
     ["do_not_locomote"] = true;
     ["distance"] = 1.25;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x15af7bd0, defined in (2649-2651)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["LOWER_SAIL_BOOST"] = {
     ["str"] = {
       [1] = "拉！";
       [2] = "吼！";
     }
     ["ghost_valid"] = false;
     ["id"] = "LOWER_SAIL_BOOST";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0x15af7b90, defined in (2645-2647)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 79;
     ["distance"] = 1.25;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xf082d00, defined in (2628-2631)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["TERRAFORM"] = {
     ["str"] = "挖";
     ["ghost_valid"] = false;
     ["id"] = "TERRAFORM";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 144;
     ["fn"] = "function: 0xc87b2d0, defined in (1533-1537)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["LOWER_SAIL"] = {
     ["str"] = "升帆";
     ["ghost_valid"] = false;
     ["id"] = "LOWER_SAIL";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0xf082ce0, defined in (2624-2626)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 78;
     ["distance"] = 1.25;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xf082cc0, defined in (2620-2622)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["STOP_STEERING_BOAT"] = {
     ["str"] = "停止掌舵";
     ["ghost_valid"] = false;
     ["id"] = "STOP_STEERING_BOAT";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 135;
     ["fn"] = "function: 0x15af7a40, defined in (2746-2751)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["PLANTSOIL"] = {
     ["str"] = "栽种";
     ["ghost_valid"] = false;
     ["id"] = "PLANTSOIL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 101;
     ["fn"] = "function: 0x1b3b6af0, defined in (2515-2527)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["REMOVE_FROM_TROPHYSCALE"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "REMOVE_FROM_TROPHYSCALE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 109;
     ["fn"] = "function: 0x15af7aa0, defined in (2783-2801)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["RETRACT_PLANK"] = {
     ["str"] = "收回";
     ["ghost_valid"] = false;
     ["id"] = "RETRACT_PLANK";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 114;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0xd337120, defined in (2713-2715)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xd337100, defined in (2708-2711)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["TAPTREE"] = {
     ["str"] = {
       ["GENERIC"] = "轻触";
       ["UNTAP"] = "取掉龙头";
     }
     ["ghost_valid"] = false;
     ["id"] = "TAPTREE";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 141;
     ["rmb"] = true;
     ["strfn"] = "function: 0x1b3b6b50, defined in (2562-2564)scripts/actions.lua";
     ["fn"] = "function: 0x1b3b6b30, defined in (2550-2560)scripts/actions.lua";
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["BEGIN_QUEST"] = {
     ["str"] = "协助";
     ["ghost_valid"] = false;
     ["id"] = "BEGIN_QUEST";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 13;
     ["fn"] = "function: 0xad8c440, defined in (2808-2813)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["USEITEM"] = {
     ["str"] = "使用";
     ["ghost_valid"] = false;
     ["id"] = "USEITEM";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 157;
     ["fn"] = "function: 0xb242ba0, defined in (1774-1782)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = false;
   }
   ["INSTALL"] = {
     ["str"] = "安装";
     ["ghost_valid"] = false;
     ["id"] = "INSTALL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 70;
     ["fn"] = "function: 0x1b3b6b10, defined in (2529-2548)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["UNEQUIP"] = {
     ["str"] = {
       ["GENERIC"] = "卸下";
       ["HEAVY"] = "丢弃";
     }
     ["ghost_valid"] = false;
     ["id"] = "UNEQUIP";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xb16b530, defined in (400-409)scripts/actions.lua";
     ["code"] = 151;
     ["strfn"] = "function: 0xc79e830, defined in (391-398)scripts/actions.lua";
     ["encumbered_valid"] = true;
     ["priority"] = -2;
     ["mount_valid"] = true;
   }
   ["TILL"] = {
     ["str"] = "耕地";
     ["ghost_valid"] = false;
     ["id"] = "TILL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 145;
     ["distance"] = 0.5;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x1b3b6ad0, defined in (2509-2513)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["BLINK"] = {
     ["str"] = {
       ["GENERIC"] = "传送";
       ["SOUL"] = "灵魂跳跃";
     }
     ["priority"] = 10;
     ["code"] = 14;
     ["ghost_valid"] = false;
     ["id"] = "BLINK";
     ["distance"] = 36;
     ["fn"] = "function: 0xc7d4470, defined in (1823-1839)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["strfn"] = "function: 0xc7d4450, defined in (1819-1821)scripts/actions.lua";
     ["rmb"] = true;
     ["mount_valid"] = true;
   }
   ["ADDWETFUEL"] = {
     ["str"] = "添加湿燃料";
     ["ghost_valid"] = false;
     ["id"] = "ADDWETFUEL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 6;
     ["fn"] = "function: 0xc87afd0, defined in (1147-1159)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["HALLOWEENMOONMUTATE"] = {
     ["str"] = "变异";
     ["ghost_valid"] = false;
     ["id"] = "HALLOWEENMOONMUTATE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 65;
     ["fn"] = "function: 0x1062f940, defined in (2417-2430)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = -1;
     ["mount_valid"] = false;
   }
   ["PET"] = {
     ["str"] = "宠物";
     ["ghost_valid"] = false;
     ["id"] = "PET";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 97;
     ["fn"] = "function: 0xf26b1b0, defined in (2194-2199)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["BAIT"] = {
     ["str"] = "放诱饵";
     ["ghost_valid"] = false;
     ["id"] = "BAIT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 11;
     ["fn"] = "function: 0xc5185c0, defined in (763-768)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["HARVEST"] = {
     ["str"] = "采收";
     ["ghost_valid"] = false;
     ["id"] = "HARVEST";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b190, defined in (1426-1445)scripts/actions.lua";
     ["code"] = 67;
     ["strfn"] = "function: 0xc87b1b0, defined in (1447-1454)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["FISH"] = {
     ["str"] = "钓鱼";
     ["ghost_valid"] = false;
     ["id"] = "FISH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 57;
     ["fn"] = "function: 0xa53eb70, defined in (920-926)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["TAKEITEM"] = {
     ["str"] = {
       ["GENERIC"] = "拿取物品";
       ["BIRDCAGE"] = "打扫";
       ["ITEM"] = "拿取{item}";
     }
     ["ghost_valid"] = false;
     ["id"] = "TAKEITEM";
     ["instant"] = false;
     ["stroverridefn"] = "function: 0xcc0f160, defined in (1796-1803)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xb242bc0, defined in (1784-1790)scripts/actions.lua";
     ["code"] = 139;
     ["strfn"] = "function: 0xcc0f140, defined in (1792-1794)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["WRITE"] = {
     ["str"] = "写下";
     ["ghost_valid"] = false;
     ["id"] = "WRITE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 163;
     ["fn"] = "function: 0x15af7700, defined in (2071-2087)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["TOSS"] = {
     ["str"] = "投掷";
     ["code"] = 147;
     ["ghost_valid"] = false;
     ["id"] = "TOSS";
     ["distance"] = 8;
     ["fn"] = "function: 0xc50bc40, defined in (2037-2054)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["rmb"] = true;
     ["mount_valid"] = true;
   }
   ["CATPLAYAIR"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "CATPLAYAIR";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 27;
     ["distance"] = 2;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xc50bc00, defined in (2018-2029)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["CASTSUMMON"] = {
     ["str"] = "召唤";
     ["ghost_valid"] = false;
     ["id"] = "CASTSUMMON";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 23;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xc7d4490, defined in (1841-1845)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["PICKUP"] = {
     ["str"] = {
       ["GENERIC"] = "拾起";
       ["HEAVY"] = "搬运";
     }
     ["ghost_valid"] = false;
     ["id"] = "PICKUP";
     ["instant"] = false;
     ["extra_arrive_dist"] = "function: 0xbb441e0, defined in (65-75)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xb16b570, defined in (418-468)scripts/actions.lua";
     ["code"] = 99;
     ["strfn"] = "function: 0xb16b550, defined in (411-416)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 1;
     ["mount_valid"] = true;
   }
   ["CASTSPELL"] = {
     ["str"] = {
       ["GENERIC"] = "施放法术";
       ["SCIENCE"] = "使用小工具";
       ["MUSIC"] = "演奏";
     }
     ["priority"] = -1;
     ["code"] = 22;
     ["ghost_valid"] = false;
     ["id"] = "CASTSPELL";
     ["distance"] = 20;
     ["fn"] = "function: 0xc7d4430, defined in (1809-1817)scripts/actions.lua";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["encumbered_valid"] = false;
     ["strfn"] = "function: 0xcc0f180, defined in (1805-1807)scripts/actions.lua";
     ["rmb"] = true;
     ["mount_valid"] = true;
   }
   ["START_CARRAT_RACE"] = {
     ["str"] = "开始胡萝卜鼠竞赛";
     ["ghost_valid"] = false;
     ["id"] = "START_CARRAT_RACE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 129;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x1062f9e0, defined in (2492-2506)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["WEIGH_ITEM"] = {
     ["str"] = "称重";
     ["ghost_valid"] = false;
     ["id"] = "WEIGH_ITEM";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 160;
     ["fn"] = "function: 0x1062f9c0, defined in (2475-2490)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["OCEAN_FISHING_CATCH"] = {
     ["str"] = "捕捉";
     ["ghost_valid"] = false;
     ["id"] = "OCEAN_FISHING_CATCH";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 93;
     ["fn"] = "function: 0x102442c0, defined in (686-694)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 6;
     ["mount_valid"] = false;
   }
   ["COMPARE_WEIGHABLE"] = {
     ["str"] = "给予";
     ["ghost_valid"] = false;
     ["id"] = "COMPARE_WEIGHABLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 35;
     ["fn"] = "function: 0x1062f9a0, defined in (2463-2473)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["STARTCHANNELING"] = {
     ["str"] = "触摸";
     ["ghost_valid"] = false;
     ["id"] = "STARTCHANNELING";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 128;
     ["distance"] = 2.1;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xeb8bbb0, defined in (2224-2226)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["HAIRBALL"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "HAIRBALL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 64;
     ["distance"] = 3;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xc50bbc0, defined in (1996-2000)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["DISMOUNT_PLANK"] = {
     ["str"] = "下来";
     ["ghost_valid"] = false;
     ["id"] = "DISMOUNT_PLANK";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 44;
     ["distance"] = 2.5;
     ["strfn"] = "function: 0xd213ab0, defined in (2687-2689)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xd213a90, defined in (2682-2685)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["STOPCONSTRUCTION"] = {
     ["str"] = {
       ["GENERIC"] = "停止建造";
       ["GENERIC_FMT"] = "停止建造{name}";
     }
     ["ghost_valid"] = false;
     ["id"] = "STOPCONSTRUCTION";
     ["instant"] = true;
     ["stroverridefn"] = "function: 0x1a0dae80, defined in (2352-2357)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 134;
     ["distance"] = 2;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0x1a0daea0, defined in (2359-2364)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["SEW"] = {
     ["str"] = {
       ["GENERIC"] = "缝补";
       ["PATCH"] = "小块地";
     }
     ["ghost_valid"] = false;
     ["id"] = "SEW";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc2ad530, defined in (500-507)scripts/actions.lua";
     ["code"] = 123;
     ["strfn"] = "function: 0xf60be80, defined in (494-498)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["BREAK"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "BREAK";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 16;
     ["rmb"] = true;
     ["strfn"] = "function: 0xa87d7d0, defined in (2272-2275)scripts/actions.lua";
     ["fn"] = "function: 0xf26b310, defined in (115-115)scripts/actions.lua";
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["BUNDLESTORE"] = {
     ["str"] = {
       ["GENERIC"] = "存放";
       ["CONSTRUCT"] = "添加材料";
     }
     ["ghost_valid"] = false;
     ["id"] = "BUNDLESTORE";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b0d0, defined in (1298-1374)scripts/actions.lua";
     ["code"] = 20;
     ["strfn"] = "function: 0xc87b0f0, defined in (1376-1384)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["BUNDLE"] = {
     ["str"] = "使用";
     ["ghost_valid"] = false;
     ["id"] = "BUNDLE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 19;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xa87d770, defined in (2235-2247)scripts/actions.lua";
     ["priority"] = 2;
     ["mount_valid"] = false;
   }
   ["MAKEMOLEHILL"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "MAKEMOLEHILL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 82;
     ["distance"] = 0;
     ["encumbered_valid"] = false;
     ["priority"] = 4;
     ["fn"] = "function: 0xf45dbb0, defined in (1894-1902)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["COMMUNEWITHSUMMONED"] = {
     ["str"] = {
       ["MAKE_DEFENSIVE"] = "安慰";
       ["MAKE_AGGRESSIVE"] = "激怒";
     }
     ["ghost_valid"] = false;
     ["id"] = "COMMUNEWITHSUMMONED";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 34;
     ["rmb"] = true;
     ["strfn"] = "function: 0xc7d44d0, defined in (1853-1855)scripts/actions.lua";
     ["fn"] = "function: 0xc7d44f0, defined in (1857-1861)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["CATPLAYGROUND"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "CATPLAYGROUND";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 28;
     ["distance"] = 1;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xc50bbe0, defined in (2002-2016)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["UPGRADE"] = {
     ["str"] = "升级";
     ["ghost_valid"] = false;
     ["id"] = "UPGRADE";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 156;
     ["rmb"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xc50bc60, defined in (2056-2062)scripts/actions.lua";
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["OCEAN_FISHING_REEL"] = {
     ["str"] = {
       ["GENERIC"] = "收线";
       ["SETHOOK"] = "下钩";
     }
     ["ghost_valid"] = false;
     ["id"] = "OCEAN_FISHING_REEL";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["code"] = 95;
     ["rmb"] = true;
     ["ghost_exclusive"] = false;
     ["do_not_locomote"] = true;
     ["silent_fail"] = true;
     ["strfn"] = "function: 0xd285110, defined in (662-667)scripts/actions.lua";
     ["fn"] = "function: 0xd285130, defined in (669-674)scripts/actions.lua";
     ["priority"] = 5;
     ["mount_valid"] = false;
   }
   ["STEAL"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "STEAL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 130;
     ["fn"] = "function: 0x13ac64e0, defined in (350-357)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["DRAW"] = {
     ["str"] = "画";
     ["ghost_valid"] = false;
     ["id"] = "DRAW";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["stroverridefn"] = "function: 0xeb8bb70, defined in (2202-2207)scripts/actions.lua";
     ["code"] = 45;
     ["fn"] = "function: 0xeb8bb90, defined in (2209-2222)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["TRAVEL"] = {
     ["str"] = "传送";
     ["ghost_valid"] = false;
     ["id"] = "TRAVEL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 148;
     ["fn"] = "function: 0xf45db50, defined in (1872-1877)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["HAUNT"] = {
     ["str"] = "闹鬼";
     ["mindistance"] = 2;
     ["ghost_valid"] = true;
     ["id"] = "HAUNT";
     ["canforce"] = true;
     ["code"] = 68;
     ["ghost_exclusive"] = true;
     ["fn"] = "function: 0xc87b450, defined in (1650-1661)scripts/actions.lua";
     ["instant"] = false;
     ["rangecheckfn"] = "function: 0xbb44140, defined in (8-16)scripts/actions.lua";
     ["priority"] = 0;
     ["encumbered_valid"] = false;
     ["mount_valid"] = false;
   }
   ["DEPLOY"] = {
     ["str"] = {
       ["GENERIC"] = "栽种";
       ["PORTABLE"] = "放置";
       ["GROUNDTILE"] = "放置地皮";
       ["WATER"] = "下水";
       ["GATE"] = "建造大门";
       ["TURRET"] = "放置";
       ["WALL"] = "建造墙";
       ["FENCE"] = "建造栅栏";
     }
     ["ghost_valid"] = false;
     ["id"] = "DEPLOY";
     ["instant"] = false;
     ["encumbered_valid"] = false;
     ["extra_arrive_dist"] = "function: 0xbb44200, defined in (77-87)scripts/actions.lua";
     ["ghost_exclusive"] = false;
     ["code"] = 40;
     ["distance"] = 1.1;
     ["strfn"] = "function: 0xd684e60, defined in (785-796)scripts/actions.lua";
     ["priority"] = 0;
     ["fn"] = "function: 0xc5185e0, defined in (770-783)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["SUMMONGUARDIAN"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "SUMMONGUARDIAN";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 137;
     ["distance"] = 5;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xd684e80, defined in (800-804)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["COMBINESTACK"] = {
     ["str"] = "合并堆放物品";
     ["ghost_valid"] = false;
     ["id"] = "COMBINESTACK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 33;
     ["fn"] = "function: 0xf45db30, defined in (1863-1870)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["MAKEBALLOON"] = {
     ["str"] = "充气";
     ["ghost_valid"] = false;
     ["id"] = "MAKEBALLOON";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 81;
     ["fn"] = "function: 0xc79e7f0, defined in (359-383)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["REVIVE_CORPSE"] = {
     ["str"] = "复活";
     ["ghost_valid"] = false;
     ["id"] = "REVIVE_CORPSE";
     ["instant"] = false;
     ["code"] = 115;
     ["priority"] = 0;
     ["ghost_exclusive"] = false;
     ["actionmeter"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0x15af7780, defined in (2115-2123)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["TEACH"] = {
     ["str"] = "学习";
     ["ghost_valid"] = false;
     ["id"] = "TEACH";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 142;
     ["fn"] = "function: 0xd5223e0, defined in (1738-1751)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["HEAL"] = {
     ["str"] = {
       ["GENERIC"] = "治疗";
       ["SELF"] = "治疗自己";
     }
     ["ghost_valid"] = false;
     ["id"] = "HEAL";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b4b0, defined in (1706-1715)scripts/actions.lua";
     ["code"] = 69;
     ["strfn"] = "function: 0xc87b490, defined in (1699-1704)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["LAYEGG"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "LAYEGG";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 74;
     ["fn"] = "function: 0xc87b310, defined in (1550-1554)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["CHANGE_TACKLE"] = {
     ["str"] = {
       ["GENERIC"] = "连接渔具";
       ["REMOVE"] = "移除渔具";
     }
     ["ghost_valid"] = false;
     ["id"] = "CHANGE_TACKLE";
     ["instant"] = true;
     ["encumbered_valid"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 30;
     ["rmb"] = true;
     ["strfn"] = "function: 0x102442e0, defined in (696-700)scripts/actions.lua";
     ["fn"] = "function: 0x10244300, defined in (702-747)scripts/actions.lua";
     ["priority"] = 3;
     ["mount_valid"] = true;
   }
   ["PLANT"] = {
     ["str"] = {
       ["GENERIC"] = "栽种";
       ["PLANTER"] = "放下";
     }
     ["ghost_valid"] = false;
     ["id"] = "PLANT";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["fn"] = "function: 0xc87b170, defined in (1407-1424)scripts/actions.lua";
     ["code"] = 100;
     ["strfn"] = "function: 0xc87b150, defined in (1403-1405)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["OCEAN_FISHING_STOP"] = {
     ["str"] = "停";
     ["ghost_valid"] = false;
     ["id"] = "OCEAN_FISHING_STOP";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 96;
     ["fn"] = "function: 0xd285150, defined in (676-684)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["OCEAN_FISHING_POND"] = {
     ["str"] = "撒";
     ["ghost_valid"] = false;
     ["id"] = "OCEAN_FISHING_POND";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 94;
     ["fn"] = "function: 0xa93c4b0, defined in (648-650)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = false;
   }
   ["MOLEPEEK"] = {
     ["str"] = "ACTION";
     ["ghost_valid"] = false;
     ["id"] = "MOLEPEEK";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 86;
     ["distance"] = 1;
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["fn"] = "function: 0xf45dbd0, defined in (1904-1909)scripts/actions.lua";
     ["mount_valid"] = false;
   }
   ["OCEAN_FISHING_CAST"] = {
     ["str"] = "撒";
     ["ghost_valid"] = false;
     ["disable_platform_hopping"] = true;
     ["instant"] = false;
     ["code"] = 92;
     ["id"] = "OCEAN_FISHING_CAST";
     ["rmb"] = true;
     ["ghost_exclusive"] = false;
     ["customarrivecheck"] = "function: 0xbb441c0, defined in (51-63)scripts/actions.lua";
     ["is_relative_to_platform"] = true;
     ["encumbered_valid"] = false;
     ["fn"] = "function: 0xa93c4d0, defined in (652-660)scripts/actions.lua";
     ["priority"] = 3;
     ["mount_valid"] = false;
   }
   ["DISMOUNT"] = {
     ["str"] = "下来";
     ["ghost_valid"] = false;
     ["id"] = "DISMOUNT";
     ["instant"] = true;
     ["ghost_exclusive"] = false;
     ["code"] = 43;
     ["rmb"] = true;
     ["encumbered_valid"] = true;
     ["fn"] = "function: 0x15af77c0, defined in (2142-2147)scripts/actions.lua";
     ["priority"] = 1;
     ["mount_valid"] = true;
   }
   ["PLAY"] = {
     ["str"] = "演奏";
     ["ghost_valid"] = false;
     ["id"] = "PLAY";
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 102;
     ["fn"] = "function: 0xc87b290, defined in (1517-1521)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["priority"] = 0;
     ["mount_valid"] = true;
   }
   ["ATTACK"] = {
     ["str"] = {
       ["GENERIC"] = "攻击";
       ["WHACK"] = "敲击";
       ["SMASHABLE"] = "砸碎";
       ["RANGEDLIGHT"] = "点燃";
       ["PROP"] = "掴";
       ["RANGEDSMOTHER"] = "扑灭";
     }
     ["ghost_valid"] = false;
     ["id"] = "ATTACK";
     ["canforce"] = true;
     ["instant"] = false;
     ["ghost_exclusive"] = false;
     ["code"] = 9;
     ["priority"] = 2;
     ["strfn"] = "function: 0x13593f40, defined in (983-1004)scripts/actions.lua";
     ["fn"] = "function: 0x13593f20, defined in (962-981)scripts/actions.lua";
     ["encumbered_valid"] = false;
     ["mount_valid"] = true;
   }
 }
 focus lost

